# Generated by Django 3.0 on 2020-01-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='halfhourly',
            options={'ordering': ['reading_date_time']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='meter',
            options={'ordering': ['id']},
        ),
    ]
